FROM debian:10 

ARG DEBIAN_FRONTEND=noninteractive

LABEL MAINTAINER Nico <nik0chan@hotmail.com>

# WORKDIR ...

#RUN     ... 

# Log output configuration  
#	 ln -sf /dev/stdout /logile_path &&  \ 
#	 ln -sf /dev/stderr /error_logfile_path && \ 

# System cleanup 
#	 rm -rf /var/lib/apt /var/lib/dpkg /var/cache/apt /usr/share/doc /usr/share/man  ...

#ADD     ...

# USER <user>
       
#EXPOSE  ...
       
# ENTRYPOINT ["executable", "param1", "param2"]

# CMD { ... } 
